import React, { useState, useEffect } from 'react';
import { Send, Hash, Clock, User, MapPin, Wifi, WifiOff } from 'lucide-react';
import { supabase } from '../services/supabaseClient';

// ==========================================
// 🔴 如何开启真实留言板 (HOW TO MAKE IT REAL)
// 1. 去 supabase.com 注册一个免费账号
// 2. 创建一个项目，得到 URL 和 ANON KEY
// 3. 在 SQL Editor 运行以下命令建表:
//    create table messages (
//      id bigint generated by default as identity primary key,
//      name text,
//      identity text,
//      content text,
//      province text,
//      created_at timestamp with time zone default timezone('utc'::text, now())
//    );
// 4. 把 URL / anon key 写进 `.env.local`（参考 `.env.example`）
// ==========================================

interface GuestMessage {
  id: string;
  name: string;
  identity: string;
  content: string;
  date: string;
  province: string;
}

const INITIAL_MESSAGES: GuestMessage[] = [
  {
    id: '1',
    name: '匿名',
    identity: '高三牲',
    content: '只要学不死，就往死里学。这句话我听了三年，现在我觉得我真的快不行了。',
    date: '2分钟前',
    province: '河南'
  },
  {
    id: '2',
    name: 'University2024',
    identity: '已毕业',
    content: '作为一个过来人，想告诉学弟学妹们：高考很重要，但它真的不是人生的全部。无论结果如何，请活下去。',
    date: '15分钟前',
    province: '山东'
  },
  {
    id: '3',
    name: 'SleepWalker',
    identity: '缺觉重症',
    content: '我想念自然醒的感觉，想念不需要看闹钟的周末。',
    date: '1小时前',
    province: '河北'
  },
  {
    id: '4',
    name: '默默',
    identity: '高一萌新',
    content: '刚上高中一个月，已经被作业量吓到了。大家都是怎么坚持下来的？',
    date: '3小时前',
    province: '江苏'
  }
];

const IDENTITIES = [
  "高三牲", "高一/高二", "已毕业", "家长", "老师", "路人"
];

const PROVINCES = [
  "河南", "河北", "山东", "江苏", "浙江", "广东", 
  "四川", "湖南", "湖北", "安徽", "其他"
];

const Guestbook: React.FC = () => {
  const [messages, setMessages] = useState<GuestMessage[]>(INITIAL_MESSAGES);
  const [name, setName] = useState('');
  const [content, setContent] = useState('');
  const [identity, setIdentity] = useState(IDENTITIES[0]);
  const [province, setProvince] = useState(PROVINCES[0]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isRealtime, setIsRealtime] = useState(false);

  // Initial Load
  useEffect(() => {
    if (supabase) {
      // --- REAL MODE: Fetch from Supabase ---
      setIsRealtime(true);
      fetchSupabaseMessages();
      
      // Real-time subscription
      const channel = supabase
        .channel('public:messages')
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, (payload) => {
          const newMsg = payload.new as any;
          const formatted: GuestMessage = {
            id: newMsg.id.toString(),
            name: newMsg.name,
            identity: newMsg.identity,
            content: newMsg.content,
            province: newMsg.province || '未知',
            date: '刚刚'
          };
          setMessages(prev => [formatted, ...prev]);
        })
        .subscribe();

      return () => { supabase.removeChannel(channel); };
    } else {
      // --- DEMO MODE: Load from LocalStorage ---
      const saved = localStorage.getItem('echo_wall_messages_v2');
      if (saved) {
        setMessages(JSON.parse(saved));
      }
    }
  }, []);

  const fetchSupabaseMessages = async () => {
    if (!supabase) return;
    const { data, error } = await supabase
      .from('messages')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);
    
    if (data && !error) {
      const formatted = data.map((msg: any) => ({
        id: msg.id.toString(),
        name: msg.name || '匿名',
        identity: msg.identity,
        content: msg.content,
        province: msg.province || '未知',
        date: new Date(msg.created_at).toLocaleDateString()
      }));
      setMessages(formatted);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!content.trim()) return;

    setIsSubmitting(true);

    const newMessageTemp: GuestMessage = {
      id: Date.now().toString(),
      name: name.trim() || '匿名',
      identity,
      content: content.trim(),
      province,
      date: '刚刚'
    };

    if (supabase) {
      // --- REAL MODE: Insert into DB ---
      const { error } = await supabase.from('messages').insert([
        { 
          name: newMessageTemp.name, 
          identity: newMessageTemp.identity, 
          content: newMessageTemp.content,
          province: newMessageTemp.province
        }
      ]);
      
      if (error) {
        console.error('Error posting:', error);
        alert('发送失败，请稍后再试');
      }
      // UI update is handled by subscription or optimistically
    } else {
      // --- DEMO MODE: Save to LocalStorage ---
      // Add slight delay to simulate network
      await new Promise(resolve => setTimeout(resolve, 600));
      const updatedMessages = [newMessageTemp, ...messages];
      setMessages(updatedMessages);
      localStorage.setItem('echo_wall_messages_v2', JSON.stringify(updatedMessages));
    }
    
    // Reset form
    setContent('');
    setName('');
    setIsSubmitting(false);
  };

  return (
    <div className="py-20 px-4 bg-slate-950 border-t border-slate-900">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-white mb-4 flex items-center justify-center gap-3">
            回声墙
            <span className={`text-xs px-2 py-1 rounded-full border flex items-center gap-1 ${isRealtime ? 'bg-green-900/30 border-green-700 text-green-400' : 'bg-slate-800 border-slate-700 text-slate-500'}`}>
              {isRealtime ? <Wifi size={12}/> : <WifiOff size={12}/>}
              {isRealtime ? "已联通全网" : "本地模式"}
            </span>
          </h2>
          <p className="text-slate-400">
            念念不忘，必有回响。<br/>
            留下你的坐标，证明我们不仅是孤岛。
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          {/* Input Form */}
          <div className="md:col-span-1">
            <div className="bg-slate-900 p-6 rounded-xl border border-slate-800 sticky top-8">
              <h3 className="text-xl font-semibold text-slate-200 mb-4 flex items-center gap-2">
                <Send size={18} className="text-red-500" />
                发出信号
              </h3>
              
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs text-slate-500 mb-1">代号 (可选)</label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="例如：深夜守望者"
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-red-500 transition-colors"
                    maxLength={10}
                  />
                </div>

                <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-xs text-slate-500 mb-1">IP 属地</label>
                      <select 
                        value={province}
                        onChange={(e) => setProvince(e.target.value)}
                        className="w-full bg-slate-800 border border-slate-700 rounded-lg px-2 py-2 text-sm text-slate-200 focus:outline-none focus:border-red-500"
                      >
                        {PROVINCES.map(p => <option key={p} value={p}>{p}</option>)}
                      </select>
                    </div>
                </div>

                <div>
                  <label className="block text-xs text-slate-500 mb-1">身份信号</label>
                  <div className="flex flex-wrap gap-2">
                    {IDENTITIES.map((id) => (
                      <button
                        key={id}
                        type="button"
                        onClick={() => setIdentity(id)}
                        className={`text-xs px-2 py-1 rounded border transition-all ${
                          identity === id 
                            ? 'bg-slate-700 border-slate-500 text-white' 
                            : 'bg-slate-800 border-slate-700 text-slate-500 hover:border-slate-600'
                        }`}
                      >
                        {id}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-xs text-slate-500 mb-1">内容</label>
                  <textarea
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    placeholder="写下你的压抑、痛苦，或者希望..."
                    className="w-full h-32 bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-red-500 transition-colors resize-none"
                    required
                  />
                </div>

                <button
                  type="submit"
                  disabled={isSubmitting || !content.trim()}
                  className="w-full bg-red-900/80 hover:bg-red-800 text-red-100 py-2.5 rounded-lg font-medium transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isSubmitting ? <span className="animate-pulse">发送中...</span> : <><Send size={16} /> 发送回声</>}
                </button>
              </form>
              
              {!isRealtime && (
                 <p className="mt-4 text-[10px] text-slate-600 text-center border-t border-slate-800 pt-2">
                   当前为本地演示模式。开发者需配置 Supabase 以开启全球同步。
                 </p>
              )}
            </div>
          </div>

          {/* Message List */}
          <div className="md:col-span-2">
            <div className="grid grid-cols-1 gap-4">
              {messages.map((msg) => (
                <div key={msg.id} className="bg-slate-900/50 p-5 rounded-xl border border-slate-800 hover:border-slate-700 transition-colors group">
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-full bg-slate-800 flex items-center justify-center text-slate-500 border border-slate-700 shrink-0">
                        <User size={16} />
                      </div>
                      <div>
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="text-slate-200 font-medium text-sm">{msg.name}</span>
                          <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                            {msg.identity}
                          </span>
                           <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-900 text-slate-500 border border-slate-800 flex items-center gap-1">
                            <MapPin size={10} />
                            {msg.province}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 text-xs text-slate-600 shrink-0">
                      <Clock size={12} />
                      <span>{msg.date}</span>
                    </div>
                  </div>
                  
                  <p className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap pl-12 border-l-2 border-slate-800 group-hover:border-red-900/50 transition-colors">
                    {msg.content}
                  </p>
                  
                  <div className="mt-4 pl-12 flex items-center gap-4">
                     {/* Simulated reaction buttons */}
                     <button className="text-xs text-slate-600 hover:text-red-400 flex items-center gap-1 transition-colors">
                        <Hash size={12} />
                        <span>共鸣</span>
                     </button>
                  </div>
                </div>
              ))}
              
              {messages.length === 0 && (
                <div className="text-center py-10 text-slate-600">
                  <p>这里还很安静... 做第一个发声的人吧。</p>
                </div>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default Guestbook;
