import React, { useState, useEffect } from 'react';
import { Send, Hash, Clock, User, MapPin, Wifi, WifiOff, Globe } from 'lucide-react';
import { getSupabaseClient, hasSupabaseConfig } from '../services/supabaseClient';
import type { RealtimeChannel } from '@supabase/supabase-js';

// ==========================================
// 🔴 如何开启真实留言板 (HOW TO MAKE IT REAL)
// 1. 去 supabase.com 注册一个免费账号
// 2. 创建一个项目，得到 URL 和 ANON KEY
// 3. 在 SQL Editor 运行以下命令建表:
//    create table messages (
//      id bigint generated by default as identity primary key,
//      name text,
//      identity text,
//      content text,
//      province text,
//      created_at timestamp with time zone default timezone('utc'::text, now())
//    );
// 4. 把 URL / anon key 写进 `.env.local`（参考 `.env.example`）
// ==========================================

interface GuestMessage {
  id: string;
  name: string;
  identity: string;
  content: string;
  date: string;
  province: string;
}

const INITIAL_MESSAGES: GuestMessage[] = [
  {
    id: '1',
    name: '匿名',
    identity: '高三牲',
    content: '只要学不死，就往死里学。这句话我听了三年，现在我觉得我真的快不行了。',
    date: '2分钟前',
    province: '河南'
  },
  {
    id: '2',
    name: 'University2024',
    identity: '已毕业',
    content: '作为一个过来人，想告诉学弟学妹们：高考很重要，但它真的不是人生的全部。无论结果如何，请活下去。',
    date: '15分钟前',
    province: '山东'
  },
  {
    id: '3',
    name: 'SleepWalker',
    identity: '缺觉重症',
    content: '我想念自然醒的感觉，想念不需要看闹钟的周末。',
    date: '1小时前',
    province: '河北'
  },
  {
    id: '4',
    name: '默默',
    identity: '高一萌新',
    content: '刚上高中一个月，已经被作业量吓到了。大家都是怎么坚持下来的？',
    date: '3小时前',
    province: '江苏'
  }
];

const IDENTITIES = [
  "高三牲", "高一/高二", "已毕业", "家长", "老师", "路人"
];

const PROVINCES = [
  "河南", "河北", "山东", "江苏", "浙江", "广东", 
  "四川", "湖南", "湖北", "安徽", "其他"
];

const Guestbook: React.FC = () => {
  const [messages, setMessages] = useState<GuestMessage[]>(INITIAL_MESSAGES);
  const [name, setName] = useState('');
  const [content, setContent] = useState('');
  const [identity, setIdentity] = useState(IDENTITIES[0]);
  const [province, setProvince] = useState(PROVINCES[0]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isRealtime, setIsRealtime] = useState(hasSupabaseConfig());

  // Initial Load
  useEffect(() => {
    let cancelled = false;
    let channel: RealtimeChannel | null = null;

    (async () => {
      const supabase = await getSupabaseClient();
      if (cancelled) return;

      if (supabase) {
        setIsRealtime(true);
        fetchSupabaseMessages(supabase);

        channel = supabase
          .channel('public:messages')
          .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, (payload) => {
            const newMsg = payload.new as any;
            const formatted: GuestMessage = {
              id: newMsg.id.toString(),
              name: newMsg.name,
              identity: newMsg.identity,
              content: newMsg.content,
              province: newMsg.province || '未知',
              date: '刚刚'
            };
            setMessages(prev => [formatted, ...prev]);
          })
          .subscribe();
      } else {
        setIsRealtime(false);
        const saved = localStorage.getItem('echo_wall_messages_v2');
        if (saved) {
          setMessages(JSON.parse(saved));
        }
      }
    })();

    return () => {
      cancelled = true;
      if (channel) {
        getSupabaseClient().then((supabase) => {
          if (supabase) supabase.removeChannel(channel);
        });
      }
    };
  }, []);

  const fetchSupabaseMessages = async (supabase: any) => {
    const { data, error } = await supabase
      .from('messages')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);
    
    if (data && !error) {
      const formatted = data.map((msg: any) => ({
        id: msg.id.toString(),
        name: msg.name || '匿名',
        identity: msg.identity,
        content: msg.content,
        province: msg.province || '未知',
        date: new Date(msg.created_at).toLocaleDateString()
      }));
      setMessages(formatted);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!content.trim()) return;

    setIsSubmitting(true);

    const newMessageTemp: GuestMessage = {
      id: Date.now().toString(),
      name: name.trim() || '匿名',
      identity,
      content: content.trim(),
      province,
      date: '刚刚'
    };

    const supabase = await getSupabaseClient();
    if (supabase) {
      // --- REAL MODE: Insert into DB ---
      const { error } = await supabase.from('messages').insert([
        { 
          name: newMessageTemp.name, 
          identity: newMessageTemp.identity, 
          content: newMessageTemp.content,
          province: newMessageTemp.province
        }
      ]);
      
      if (error) {
        console.error('Error posting:', error);
        alert('发送失败，请稍后再试');
      }
      // UI update is handled by subscription or optimistically
    } else {
      // --- DEMO MODE: Save to LocalStorage ---
      // Add slight delay to simulate network
      await new Promise(resolve => setTimeout(resolve, 600));
      const updatedMessages = [newMessageTemp, ...messages];
      setMessages(updatedMessages);
      localStorage.setItem('echo_wall_messages_v2', JSON.stringify(updatedMessages));
    }
    
    // Reset form
    setContent('');
    setName('');
    setIsSubmitting(false);
  };

  return (
    <div className="py-24 px-4 bg-slate-950 border-t border-slate-900 relative">
      <div className="max-w-6xl mx-auto relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-white mb-4 flex items-center justify-center gap-3">
            <Globe size={32} className="text-slate-500"/>
            回声墙
          </h2>
           <div className="inline-flex items-center gap-2 px-3 py-1 bg-slate-900 rounded-full border border-slate-800">
             <span className={`w-2 h-2 rounded-full ${isRealtime ? 'bg-green-500 animate-pulse' : 'bg-slate-500'}`}></span>
             <span className="text-xs text-slate-400 font-mono uppercase tracking-wider">
               {isRealtime ? "Live Connection" : "Local Mode"}
             </span>
           </div>
          <p className="text-slate-400 mt-6 text-lg max-w-2xl mx-auto">
            念念不忘，必有回响。留下你的坐标，证明我们不仅是孤岛。
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
          
          {/* Input Form */}
          <div className="md:col-span-4 sticky top-8">
            <div className="glass-panel p-6 rounded-2xl">
              <h3 className="text-lg font-bold text-slate-200 mb-6 flex items-center gap-2">
                <Send size={18} className="text-red-500" />
                发出信号
              </h3>
              
              <form onSubmit={handleSubmit} className="space-y-5">
                <div>
                  <label className="block text-xs text-slate-400 uppercase tracking-wider mb-2">Code Name</label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="例如：深夜守望者"
                    className="w-full bg-slate-800/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-red-500/20 focus:border-red-500/30 transition-all"
                    maxLength={10}
                  />
                </div>

                <div>
                  <label className="block text-xs text-slate-400 uppercase tracking-wider mb-2">Location</label>
                  <div className="relative">
                    <MapPin size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
                    <select 
                        value={province}
                        onChange={(e) => setProvince(e.target.value)}
                        className="w-full bg-slate-800/40 border border-white/10 rounded-xl pl-9 pr-4 py-3 text-sm text-slate-200 focus:outline-none focus:ring-2 focus:ring-red-500/20 focus:border-red-500/30 appearance-none cursor-pointer"
                    >
                        {PROVINCES.map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-xs text-slate-400 uppercase tracking-wider mb-2">Identity Signal</label>
                  <div className="flex flex-wrap gap-2">
                    {IDENTITIES.map((id) => (
                      <button
                        key={id}
                        type="button"
                        onClick={() => setIdentity(id)}
                        className={`text-xs px-3 py-1.5 rounded-md border transition-all ${
                          identity === id 
                            ? 'bg-slate-700 text-white border-slate-500 shadow-sm' 
                            : 'bg-slate-800/30 text-slate-500 border-slate-700 hover:border-slate-600 hover:text-slate-300'
                        }`}
                      >
                        {id}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-xs text-slate-400 uppercase tracking-wider mb-2">Message</label>
                  <textarea
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    placeholder="写下你的压抑、痛苦，或者希望..."
                    className="w-full h-32 bg-slate-800/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-red-500/20 focus:border-red-500/30 transition-all resize-none"
                    required
                  />
                </div>

                <button
                  type="submit"
                  disabled={isSubmitting || !content.trim()}
                  className="w-full bg-gradient-to-r from-red-900/80 to-red-800/80 hover:from-red-800 hover:to-red-700 text-white py-3 rounded-xl font-bold transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_0_20px_rgba(153,27,27,0.22)] hover:shadow-[0_0_34px_rgba(153,27,27,0.35)] transform hover:-translate-y-0.5"
                >
                  {isSubmitting ? <span className="animate-pulse">Sending...</span> : <><Send size={16} /> 发送回声</>}
                </button>
              </form>
            </div>
          </div>

          {/* Message List */}
          <div className="md:col-span-8">
            <div className="grid grid-cols-1 gap-6">
              {messages.map((msg) => (
                <div key={msg.id} className="glass-panel p-6 rounded-xl hover:bg-slate-800/40 transition-colors group relative overflow-hidden">
                  <div className="flex justify-between items-start mb-4 relative z-10">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 rounded-full bg-gradient-to-br from-slate-700 to-slate-800 flex items-center justify-center text-slate-400 border border-slate-600 shrink-0 shadow-inner">
                        <User size={18} />
                      </div>
                      <div>
                        <div className="flex flex-wrap items-center gap-3">
                          <span className="text-slate-100 font-bold text-base">{msg.name}</span>
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-800/80 text-slate-400 border border-slate-700/50 uppercase tracking-wide font-medium">
                            {msg.identity}
                          </span>
                        </div>
                        <div className="flex items-center gap-2 mt-1 text-xs text-slate-500">
                           <span className="flex items-center gap-1"><MapPin size={10} /> {msg.province}</span>
                           <span className="w-1 h-1 rounded-full bg-slate-600"></span>
                           <span className="flex items-center gap-1"><Clock size={10} /> {msg.date}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="relative z-10 pl-14">
                    <p className="text-slate-300 text-sm leading-7 whitespace-pre-wrap font-serif">
                        {msg.content}
                    </p>
                    
                    <div className="mt-4 flex items-center gap-4 opacity-50 group-hover:opacity-100 transition-opacity">
                        <button className="text-xs text-slate-500 hover:text-red-400 flex items-center gap-1.5 transition-colors px-2 py-1 rounded hover:bg-slate-800">
                            <Hash size={12} />
                            <span>共鸣</span>
                        </button>
                    </div>
                  </div>

                  {/* Decorative faint quote mark */}
                  <div className="absolute top-4 right-6 text-8xl font-serif text-slate-800/30 select-none pointer-events-none">”</div>
                </div>
              ))}
              
              {messages.length === 0 && (
                <div className="text-center py-20 text-slate-600 glass-panel rounded-xl">
                  <p>这里还很安静... 做第一个发声的人吧。</p>
                </div>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default Guestbook;
